---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: springboot
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: springboot
  interval: 30s
  targetNamespace: springboot
  values:
    image:
      name: tjjoshua/spingboot-mongo
      tag: latest


